"""
V3 Notebook Generation
-----------------------
- Infers problem type from V1 + V2
- Selects model based on dataset size and problem type
- Generates a complete runnable .ipynb via Ollama LLM
- 6 sections: Title → Load+EDA → Split → Preprocess → Model → Train+CV → Summary
"""

import json
import os
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
from researchforge.config.settings import Settings
import requests


class V3Notebook:
    def __init__(self):
        self.settings = Settings()

    def generate(
        self,
        topic: str,
        v1_findings: dict,
        v2_dataset: dict,
        model_override: str = None,
    ) -> dict:
        problem_type = (
            v2_dataset.get("problem_type")
            or v1_findings.get("problem_type", "classification")
        )
        dataset_name = v2_dataset.get("name", "dataset")
        label_col    = v2_dataset.get("label_column", "target")
        risks        = v2_dataset.get("risks", [])

        model_name = model_override or self._select_model(problem_type, v2_dataset)
        metric_name, expected_range = self._expected_metrics(problem_type, model_name)

        # Build cells
        nb = new_notebook()
        nb.cells = [
            self._title_cell(topic, model_name, metric_name, expected_range),
            self._cell_1_load_eda(dataset_name, label_col, problem_type),
            self._cell_2_split(problem_type, label_col, risks),
            self._cell_3_preprocess(problem_type, risks),
            self._cell_4_model(problem_type, model_name, label_col),
            self._cell_5_train(metric_name),
            self._cell_6_summary(topic, model_name, metric_name, expected_range, v1_findings),
        ]

        # Save
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic)[:40]
        nb_path = f"researchforge_{safe_topic}.ipynb"
        with open(nb_path, "w", encoding="utf-8") as f:
            nbformat.write(nb, f)

        return {
            "notebook_path": nb_path,
            "model":         model_name,
            "metric_name":   metric_name,
            "expected_range": expected_range,
            "problem_type":  problem_type,
        }

    # ── Model selection ───────────────────────────────────────────

    def _select_model(self, problem_type: str, v2_dataset: dict) -> str:
        if problem_type == "graph":
            return "GATConv"
        if problem_type == "nlp":
            return "DistilBERT"

        shape = v2_dataset.get("shape", "")
        try:
            rows = int(shape.split("rows")[0].replace(",", "").strip())
        except Exception:
            rows = 10_000

        if rows < 10_000:
            return "XGBoost"
        if rows < 100_000:
            return "LightGBM"
        return "PyTorch MLP + LightGBM ensemble"

    def _expected_metrics(self, problem_type: str, model: str):
        defaults = {
            "classification": ("F1-macro",  "0.78–0.86"),
            "regression":     ("RMSE",       "model-dependent"),
            "graph":          ("F1-macro",  "0.71–0.82"),
            "nlp":            ("Accuracy",  "0.82–0.90"),
        }
        return defaults.get(problem_type, ("F1-macro", "0.75–0.85"))

    # ── Notebook cells ────────────────────────────────────────────

    def _title_cell(self, topic, model, metric, expected):
        return new_markdown_cell(
            f"# ResearchForge — Generated Notebook\n"
            f"**Topic**: {topic}  \n"
            f"**Model**: `{model}`  \n"
            f"**Expected {metric}**: `{expected}`  \n\n"
            f"> Auto-generated by ResearchForge. "
            f"Review each section before running on GPU.\n"
        )

    def _cell_1_load_eda(self, dataset_name, label_col, problem_type):
        code = f"""\
# ── SECTION 1: Load + EDA ──────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ⚠ Replace with your actual dataset path:
DATASET_PATH = "{dataset_name}"

df = pd.read_csv(DATASET_PATH)
print(f"Shape: {{df.shape}}")
print(df.head())
print("\\nMissing values:")
print(df.isnull().sum())
print(f"\\nDuplicate rows: {{df.duplicated().sum()}}")

# Target distribution
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
df["{label_col}"].value_counts().plot(kind="bar", ax=axes[0], title="Target distribution")

# Correlation heatmap (numeric columns)
numeric_df = df.select_dtypes(include=[np.number])
if len(numeric_df.columns) > 1:
    sns.heatmap(numeric_df.corr(), ax=axes[1], cmap="coolwarm", annot=False)
    axes[1].set_title("Correlation heatmap")

plt.tight_layout()
plt.savefig("eda_overview.png", dpi=120)
plt.show()
print("EDA complete. Saved: eda_overview.png")
"""
        return new_code_cell(code)

    def _cell_2_split(self, problem_type, label_col, risks):
        smote_comment = (
            "# NOTE: SMOTE is applied in Section 3 — class imbalance detected"
            if any("imbalance" in r for r in risks)
            else ""
        )
        code = f"""\
# ── SECTION 2: Split ──────────────────────────────────────────
from sklearn.model_selection import train_test_split, StratifiedKFold

X = df.drop(columns=["{label_col}"])
y = df["{label_col}"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print(f"Train: {{X_train.shape}}, Test: {{X_test.shape}}")
print(f"Class balance (train): {{y_train.value_counts().to_dict()}}")

# 5-fold stratified cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
{smote_comment}
"""
        return new_code_cell(code)

    def _cell_3_preprocess(self, problem_type, risks):
        smote_code = ""
        if any("imbalance" in r for r in risks):
            smote_code = """\

# Apply SMOTE on training data only (imbalance detected by V2 audit)
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_num = X_train.select_dtypes(include=[np.number]).fillna(0)
X_train, y_train = smote.fit_resample(X_train_num, y_train)
print(f"After SMOTE: {{X_train.shape}}")
"""

        code = f"""\
# ── SECTION 3: Preprocess ────────────────────────────────────
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
import numpy as np

# Encode categoricals
cat_cols = X_train.select_dtypes(include=["object"]).columns.tolist()
le_encoders = {{}}
for col in cat_cols:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col].astype(str))
    X_test[col]  = le.transform(X_test[col].astype(str))
    le_encoders[col] = le

# Impute + scale numeric
num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
imputer = SimpleImputer(strategy="median")
scaler  = StandardScaler()

X_train[num_cols] = scaler.fit_transform(imputer.fit_transform(X_train[num_cols]))
X_test[num_cols]  = scaler.transform(imputer.transform(X_test[num_cols]))
{smote_code}
print("Preprocessing complete.")
"""
        return new_code_cell(code)

    def _cell_4_model(self, problem_type, model_name, label_col):
        if problem_type == "graph":
            code = self._gnn_model_cell(label_col)
        elif problem_type == "nlp":
            code = self._nlp_model_cell(label_col)
        elif model_name == "XGBoost":
            code = self._xgboost_cell()
        elif "LightGBM" in model_name:
            code = self._lightgbm_cell()
        else:
            # MLP ensemble fallback
            code = self._mlp_ensemble_cell()
        return new_code_cell(code)

    def _gnn_model_cell(self, label_col):
        return """\
# ── SECTION 4: GNN Model (PyTorch Geometric) ─────────────────
import torch
import torch.nn.functional as F
from torch_geometric.nn import GATConv
from torch_geometric.data import Data, DataLoader

# Device — uses your GPU automatically
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

class ResearchForgeGNN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=4):
        super().__init__()
        self.conv1 = GATConv(in_channels, hidden_channels, heads=heads, dropout=0.3)
        self.conv2 = GATConv(hidden_channels * heads, hidden_channels, heads=1)
        self.classifier = torch.nn.Linear(hidden_channels, out_channels)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = F.dropout(x, p=0.3, training=self.training)
        x = F.elu(self.conv1(x, edge_index))
        x = F.dropout(x, p=0.3, training=self.training)
        x = self.conv2(x, edge_index)
        return self.classifier(x[0])  # global node / shot target

# Build graph dataset using ResearchForge GraphBuilder:
from researchforge.utils.graph_builder import GraphBuilder

POSITION_COLS    = ["x", "y", "velocity_x", "velocity_y"]  # ← update to your actual columns
LABEL_COL        = \"""" + label_col + """\"""
PROXIMITY_THRESH = 3.0  # meters

builder    = GraphBuilder()
graph_list = builder.build_from_dataframe(
    df, position_cols=POSITION_COLS,
    label_col=LABEL_COL,
    proximity_threshold=PROXIMITY_THRESH,
)
print(f"Built {len(graph_list)} graph samples")
print(f"Sample: {graph_list[0]}")

loader = DataLoader(graph_list, batch_size=32, shuffle=True)

n_features = graph_list[0].x.shape[1]
n_classes  = df[LABEL_COL].nunique()
model = ResearchForgeGNN(n_features, hidden_channels=64, out_channels=n_classes).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
print(f"GNN model: {sum(p.numel() for p in model.parameters()):,} parameters")
"""

    def _nlp_model_cell(self, label_col):
        return f"""\
# ── SECTION 4: NLP Model (DistilBERT fine-tune) ───────────────
import torch
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer, TrainingArguments,
)
from datasets import Dataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {{device}}")

# ⚠ Update TEXT_COL to the column containing your text
TEXT_COL  = "text"
LABEL_COL = "{label_col}"

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

def tokenize(batch):
    return tokenizer(batch[TEXT_COL], truncation=True, padding=True, max_length=128)

hf_dataset = Dataset.from_pandas(df[[TEXT_COL, LABEL_COL]])
hf_dataset = hf_dataset.map(tokenize, batched=True)

n_labels = df[LABEL_COL].nunique()
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=n_labels
).to(device)

training_args = TrainingArguments(
    output_dir="./rf_nlp_output",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=torch.cuda.is_available(),
)
print("DistilBERT model ready.")
"""

    def _xgboost_cell(self):
        return """\
# ── SECTION 4: XGBoost Model ──────────────────────────────────
import xgboost as xgb
from sklearn.metrics import f1_score, classification_report
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# XGBoost uses CUDA automatically when device="cuda"
model = xgb.XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="mlogloss",
    device="cuda" if torch.cuda.is_available() else "cpu",
    random_state=42,
)
print("XGBoost model ready.")
"""

    def _lightgbm_cell(self):
        return """\
# ── SECTION 4: LightGBM Model ─────────────────────────────────
import lightgbm as lgb
from sklearn.metrics import f1_score
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model = lgb.LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=63,
    device="gpu" if torch.cuda.is_available() else "cpu",
    random_state=42,
    n_jobs=-1,
)
print("LightGBM model ready.")
"""

    def _mlp_ensemble_cell(self):
        return """\
# ── SECTION 4: PyTorch MLP + LightGBM Ensemble ────────────────
import torch
import torch.nn as nn
import lightgbm as lgb
from sklearn.metrics import f1_score

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# PyTorch MLP
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Linear(hidden_dim // 2, output_dim),
        )
    def forward(self, x): return self.net(x)

n_features = X_train.shape[1]
n_classes  = len(set(y_train))
mlp_model  = MLP(n_features, 256, n_classes).to(device)
optimizer  = torch.optim.AdamW(mlp_model.parameters(), lr=1e-3, weight_decay=1e-4)

# LightGBM for ensemble
lgb_model = lgb.LGBMClassifier(
    n_estimators=500, learning_rate=0.05, num_leaves=63,
    device="gpu" if torch.cuda.is_available() else "cpu",
    random_state=42, n_jobs=-1,
)
print("MLP + LightGBM ensemble ready.")
"""

    def _cell_5_train(self, metric_name):
        code = f"""\
# ── SECTION 5: Train + 5-fold CV ──────────────────────────────
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score, classification_report
import numpy as np

# 5-fold cross-validation
scores = cross_val_score(
    model, X_train, y_train,
    cv=cv, scoring="f1_macro", n_jobs=-1,
)
print(f"CV {metric_name}: {{scores.mean():.3f}} ± {{scores.std():.3f}}")

# Final fit on full training set
model.fit(X_train, y_train)

# Holdout evaluation
y_pred     = model.predict(X_test)
final_score = f1_score(y_test, y_pred, average="macro")
print(f"\\nHoldout {metric_name}: {{final_score:.3f}}")
print("\\nClassification Report:")
print(classification_report(y_test, y_pred))
"""
        return new_code_cell(code)

    def _cell_6_summary(self, topic, model, metric, expected, v1_findings):
        key_findings_json = json.dumps(v1_findings.get("key_findings", [])[:3])
        limitations_json  = json.dumps(v1_findings.get("limitations", [])[:2])
        code = f"""\
# ── SECTION 6: Business Summary ───────────────────────────────
import json, joblib

summary = {{
    "topic":    "{topic}",
    "model":    "{model}",
    "metric":   "{metric}",
    "expected_range": "{expected}",
    "key_research_findings": {key_findings_json},
    "dataset_risks": {limitations_json},
    "next_steps": [
        "Run: researchforge run \\"{topic}\\" (autoresearch overnight optimization)",
        "Review EDA plots in eda_overview.png",
        "Try --model gnn if using player-tracking / graph data",
    ],
}}
print(json.dumps(summary, indent=2))

# Save model
joblib.dump(model, "researchforge_model.pkl")
print("\\nModel saved to researchforge_model.pkl")
"""
        return new_code_cell(code)
